name: neith
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  wizard_router: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_icon.png
    - assets/meta_icon.png
    - assets/notfound.png
    - assets/recommendationplace.png
    - assets/wizard-flow-1.png
    - assets/generating-travel-plan.png
    - assets/icon/gmail_groups.png
    - assets/icon/schedule.png
    - assets/icon/today.png
    - assets/travel_plan_data.json
